apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"dependencies.box.com"},"spec":{"group":"box.com","names":{"kind":"Dependencies","plural":"dependencies","singular":"dependencies"},"scope":"Namespaced","versions":[{"name":"v1","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"services":{"items":{"properties":{"sin":{"type":"string"}},"required":["sin"],"type":"object"},"type":"array"}},"required":["services"],"type":"object"}},"required":["spec"],"type":"object"}},"served":true,"storage":true}]}}
  creationTimestamp: "2021-10-21T18:48:45Z"
  generation: 1
  name: dependencies.box.com
  resourceVersion: "1767"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/dependencies.box.com
  uid: 2a8e3865-0dd9-4bf0-a6fb-513c1e413ba2
spec:
  conversion:
    strategy: None
  group: box.com
  names:
    kind: Dependencies
    listKind: DependenciesList
    plural: dependencies
    singular: dependencies
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              services:
                items:
                  properties:
                    sin:
                      type: string
                  required:
                  - sin
                  type: object
                type: array
            required:
            - services
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: Dependencies
    listKind: DependenciesList
    plural: dependencies
    singular: dependencies
  conditions:
  - lastTransitionTime: "2021-10-21T18:48:45Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-10-21T18:48:45Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
